#!/usr/bin/env node
/**
 * readme-status.mjs — the only place test numbers enter the README.
 *
 *   node scripts/evidence/readme-status.mjs --write   # refresh the block from gate-evidence/summary.json
 *   node scripts/evidence/readme-status.mjs --check   # fail when the committed block is not what the summary says
 *   node scripts/evidence/readme-status.mjs --print   # print the block (CI job summary)
 *
 * The block between <!-- evidence:begin --> and <!-- evidence:end --> is generated; nothing outside it may
 * state a test count (scripts/lint-docs.mjs enforces that).
 */
import { fileURLToPath } from "node:url";
import { dirname as pathDirname } from "node:path";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const HERE = pathDirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..");
const README = resolve(ROOT, "README.md");
const SUMMARY = resolve(ROOT, process.argv.includes("--summary") ? process.argv[process.argv.indexOf("--summary") + 1] : "gate-evidence/summary.json");
const BEGIN = "<!-- evidence:begin -->";
const END = "<!-- evidence:end -->";

const s = JSON.parse(readFileSync(SUMMARY, "utf8"));
const lines = [BEGIN, "", "_Generated by `scripts/evidence/readme-status.mjs` from the last full gate run (`gate-evidence/summary.json`); do not edit by hand._", "", "| area | suites | tests |", "|---|---|---|"];
for (const [id, a] of Object.entries(s.areas)) if (a.tests) lines.push(`| ${a.label} | ${a.suites} | ${a.tests} |`);
lines.push(`| **total** | **${s.total.suites}** | **${s.total.tests}** (${s.total.passed} passed, ${s.total.failed} failed, ${s.total.skipped} skipped) |`, "", "| gate | status |", "|---|---|");
for (const g of s.gates) lines.push(`| ${g.gate} | ${g.status} |`);
lines.push("", END);
const block = lines.join("\n");

function run() {
  if (process.argv.includes("--print")) { console.log(block); return 0; }

  const text = readFileSync(README, "utf8");
  const b = text.indexOf(BEGIN);
  const e = text.indexOf(END);
  if (b < 0 || e < b) { console.error(`README.md has no ${BEGIN} ... ${END} block`); return 2; }

  if (process.argv.includes("--check")) {
    if (text.slice(b, e + END.length) !== block) { console.error("README status block is stale: run the gates, then node scripts/evidence/readme-status.mjs --write"); return 1; }
    console.log("README status block matches gate-evidence/summary.json");
    return 0;
  }
  writeFileSync(README, text.slice(0, b) + block + text.slice(e + END.length));
  console.log("README status block refreshed");
  return 0;
}

// exitCode, not process.exit(): a piped stdout is flushed before the process ends
process.exitCode = run();
