#!/usr/bin/env node
/**
 * branch-ledger.mjs — deterministic branch ledger for a repository.
 *
 * Reads remote refs from git (never from memory), computes for each branch:
 *   ahead/behind vs the default branch, ahead/behind vs the trunk branch,
 *   number of commits NOT yet applied to the trunk (git cherry), last commit,
 * and joins them with the human-authored disposition map.
 *
 * Usage:
 *   node scripts/closure/branch-ledger.mjs --repo <path> --default <branch> --trunk <branch> \
 *        --dispositions <file.json> [--out <file.json>] [--md <file.md>]
 *
 * Dispositions are never deleted from the remote by this tool; the ledger only records
 * what must happen (the repository owner's rule: no deletion of remote history branches).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

function arg(name, def) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
}
const repo = arg("repo", process.cwd());
const defaultBranch = arg("default");
const trunk = arg("trunk");
const dispFile = arg("dispositions");
const outFile = arg("out");
const mdFile = arg("md");
if (!defaultBranch || !trunk || !dispFile) {
  console.error("usage: branch-ledger.mjs --repo <path> --default <b> --trunk <b> --dispositions <f> [--out f] [--md f]");
  process.exit(2);
}

const git = (...a) => execFileSync("git", ["-C", repo, ...a], { encoding: "utf8" }).trim();
const tryGit = (...a) => { try { return git(...a); } catch { return null; } };

const dispositions = JSON.parse(readFileSync(dispFile, "utf8"));
const refs = git("for-each-ref", "--format=%(refname:short)\t%(objectname)", "refs/remotes/origin")
  .split("\n").filter(Boolean)
  .map((l) => l.split("\t"))
  .filter(([n]) => n !== "origin" && n !== "origin/HEAD");

const rows = [];
for (const [ref, sha] of refs) {
  const name = ref.replace(/^origin\//, "");
  const [bDef, aDef] = git("rev-list", "--left-right", "--count", `origin/${defaultBranch}...${ref}`).split(/\s+/).map(Number);
  const trunkRef = `origin/${trunk}`;
  const hasTrunk = tryGit("rev-parse", "--verify", trunkRef) !== null;
  let aTr = null, bTr = null, unapplied = null, containedInTrunk = null;
  if (hasTrunk && ref !== trunkRef) {
    [bTr, aTr] = git("rev-list", "--left-right", "--count", `${trunkRef}...${ref}`).split(/\s+/).map(Number);
    const cherry = git("cherry", trunkRef, ref).split("\n").filter(Boolean);
    unapplied = cherry.filter((l) => l.startsWith("+")).length;
    containedInTrunk = tryGit("merge-base", "--is-ancestor", ref, trunkRef) !== null;
  }
  const last = git("log", "-1", "--format=%cs\t%s", ref).split("\t");
  const d = dispositions[name] ?? { disposition: "UNCLASSIFIED", reason: "no entry in disposition map" };
  rows.push({
    branch: name,
    sha,
    aheadOfDefault: aDef,
    behindDefault: bDef,
    aheadOfTrunk: aTr,
    unappliedToTrunk: unapplied,
    containedInTrunkHistory: containedInTrunk,
    lastCommitDate: last[0],
    lastCommitSubject: last[1],
    disposition: d.disposition,
    reason: d.reason,
    action: d.action ?? null,
  });
}
rows.sort((a, b) => a.branch.localeCompare(b.branch));
const unclassified = rows.filter((r) => r.disposition === "UNCLASSIFIED").map((r) => r.branch);

const ledger = {
  repository: git("config", "--get", "remote.origin.url").replace(/\.git$/, ""),
  defaultBranch,
  trunkBranch: trunk,
  defaultBranchSha: git("rev-parse", `origin/${defaultBranch}`),
  trunkSha: tryGit("rev-parse", `origin/${trunk}`),
  policy: "No remote branch is deleted by this closure. Disposition DEPRECATED_* branches are listed for the owner to retire.",
  unclassified,
  branches: rows,
};
if (outFile) writeFileSync(outFile, JSON.stringify(ledger, null, 2) + "\n");
if (mdFile) {
  const md = [];
  md.push(`# Branch ledger — ${ledger.repository}`, "");
  md.push(`default: \`${defaultBranch}\` @ \`${ledger.defaultBranchSha.slice(0, 10)}\` · trunk: \`${trunk}\` @ \`${(ledger.trunkSha ?? "n/a").slice(0, 10)}\``, "");
  md.push("Generated by `scripts/closure/branch-ledger.mjs`; do not edit by hand.", "");
  md.push("| branch | ahead/behind default | unapplied to trunk | in trunk history | disposition | reason |", "|---|---|---|---|---|---|");
  for (const r of rows) {
    md.push(`| \`${r.branch}\` | +${r.aheadOfDefault}/-${r.behindDefault} | ${r.unappliedToTrunk ?? "—"} | ${r.containedInTrunkHistory ?? "—"} | **${r.disposition}** | ${r.reason} |`);
  }
  writeFileSync(mdFile, md.join("\n") + "\n");
}
console.log(`ledger rows=${rows.length} unclassified=${unclassified.length}`);
if (unclassified.length) { console.error("UNCLASSIFIED:", unclassified.join(", ")); process.exit(1); }
