#!/usr/bin/env node
/**
 * rule-ledger.mjs — builds docs/closure/RULE-LEDGER.{json,md}.
 *
 * Every threshold-shaped site found by scan-aesthetic-constants.mjs in BOTH repositories
 * must be covered either by an out-of-scope file class (with a stated reason) or by a
 * ledger entry carrying one of the four dispositions. Anything uncovered fails the build:
 * "no unclassified aesthetic constant" is enforced, not asserted.
 *
 * Usage:
 *   node scripts/closure/rule-ledger.mjs --dc <path> --skill <path> --source <rule-ledger.source.json> \
 *        [--out <json>] [--md <md>]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { scan } from "./scan-aesthetic-constants.mjs";

function arg(n, d) { const i = process.argv.indexOf(`--${n}`); return i >= 0 ? process.argv[i + 1] : d; }
const dc = arg("dc"), skill = arg("skill"), src = arg("source");
if (!dc || !skill || !src) { console.error("usage: rule-ledger.mjs --dc <p> --skill <p> --source <f> [--out f] [--md f]"); process.exit(2); }

const globToRe = (g) => new RegExp("^" + g.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "\u0000").replace(/\*/g, "[^/]*").replace(/\u0000/g, ".*") + "$");
const source = JSON.parse(readFileSync(src, "utf8"));
const sha = (p) => { try { return execFileSync("git", ["-C", p, "rev-parse", "HEAD"], { encoding: "utf8" }).trim(); } catch { return null; } };

const repos = [
  { name: "design-compiler", path: dc, profile: "dc" },
  { name: "chinese-aesthetic-skill", path: skill, profile: "skill" },
];

const classRes = source.file_classes.map((c) => ({ ...c, re: globToRe(c.glob), exRes: (c.exceptions ?? []).map(globToRe) }));
const entryRes = source.entries.map((e) => ({ ...e, res: e.files.map(globToRe) }));

const result = { ledger_version: source.ledger_version, baseline: {}, summary: {}, classes: {}, entries: [], uncovered: [] };
const bucketSites = new Map(); // key -> sites
for (const repo of repos) {
  result.baseline[repo.name] = { path: repo.name, head: sha(repo.path) };
  const sites = scan(repo.path, repo.profile).filter((s) => !s.comment);
  for (const s of sites) {
    let key = null;
    const entry = entryRes.find((e) => e.repo === repo.name && e.res.some((r) => r.test(s.file)));
    if (entry) key = `entry:${entry.id}`;
    else {
      const cls = classRes.find((c) => c.repo === repo.name && c.re.test(s.file) && !c.exRes.some((r) => r.test(s.file)));
      if (cls) key = `class:${cls.class}`;
    }
    if (!key) { result.uncovered.push({ repo: repo.name, file: s.file, line: s.line, text: s.text }); continue; }
    if (!bucketSites.has(key)) bucketSites.set(key, []);
    bucketSites.get(key).push({ repo: repo.name, file: s.file, line: s.line, kind: s.kind });
  }
}
for (const [key, sites] of bucketSites) {
  if (key.startsWith("class:")) {
    const c = key.slice(6);
    result.classes[c] = { reason: source.out_of_scope_classes[c], sites: sites.length, files: [...new Set(sites.map((s) => s.file))].length };
  }
}
for (const e of source.entries) {
  const sites = bucketSites.get(`entry:${e.id}`) ?? [];
  result.entries.push({
    id: e.id, repo: e.repo, disposition: e.disposition, concept: e.concept, canonical: e.canonical,
    conflicts: e.conflicts ?? [], runtime: e.runtime ?? null, docs: e.docs ?? null,
    files: e.files, sites: sites.length, status: "OPEN",
  });
}
const byDisp = {};
for (const e of result.entries) byDisp[e.disposition] = (byDisp[e.disposition] ?? 0) + e.sites;
result.summary = {
  total_sites: [...bucketSites.values()].reduce((a, b) => a + b.length, 0),
  uncovered_sites: result.uncovered.length,
  sites_by_disposition: byDisp,
  sites_out_of_scope: Object.fromEntries(Object.entries(result.classes).map(([k, v]) => [k, v.sites])),
};

const out = arg("out"), md = arg("md");
if (out) writeFileSync(out, JSON.stringify(result, null, 2) + "\n");
if (md) {
  const L = [];
  L.push("# Rule ledger", "", "Generated by `scripts/closure/rule-ledger.mjs` from a live scan of both repositories; do not edit by hand.", "");
  L.push(`Baseline: design-compiler \`${(result.baseline["design-compiler"].head ?? "").slice(0, 10)}\` · chinese-aesthetic-skill \`${(result.baseline["chinese-aesthetic-skill"].head ?? "").slice(0, 10)}\``, "");
  L.push(`Sites scanned: **${result.summary.total_sites}** · uncovered: **${result.summary.uncovered_sites}**`, "");
  L.push("## Dispositions", "", ...Object.entries(source.dispositions).map(([k, v]) => `- **${k}** — ${v}`), "");
  L.push("## Entries", "", "| id | repo | disposition | sites | canonical | conflicts |", "|---|---|---|---|---|---|");
  for (const e of result.entries) L.push(`| \`${e.id}\` | ${e.repo} | **${e.disposition}** | ${e.sites} | ${e.canonical} | ${e.conflicts.length ? e.conflicts.join("<br>") : "—"} |`);
  L.push("", "## Out of scope (stays in design-compiler / not aesthetic)", "", "| class | sites | files | reason |", "|---|---|---|---|");
  for (const [k, v] of Object.entries(result.classes)) L.push(`| ${k} | ${v.sites} | ${v.files} | ${v.reason} |`);
  writeFileSync(md, L.join("\n") + "\n");
}
console.log(`sites=${result.summary.total_sites} uncovered=${result.summary.uncovered_sites} entries=${result.entries.length}`);
if (result.uncovered.length) {
  for (const u of result.uncovered.slice(0, 40)) console.error(`UNCOVERED ${u.repo}:${u.file}:${u.line}: ${u.text}`);
  process.exit(1);
}
